// Custom Cloudflare Worker entry point.
//
// It re-uses the fetch handler generated by OpenNext and adds a scheduled
// handler that retries delivery of any form submissions whose notification
// email has not yet succeeded. This is what makes form delivery zero-loss:
// submissions are always stored in D1, and this cron keeps retrying the email
// until it goes through.

// `./.open-next/worker.js` is generated by `opennextjs-cloudflare build`, so it
// does not exist when Next.js type-checks this file during the build.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore generated at build time
import { default as handler } from "./.open-next/worker.js";

import { flushPendingSubmissions } from "./lib/form-delivery";

export default {
  fetch: handler.fetch,

  async scheduled(
    _event: ScheduledController,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ) {
    ctx.waitUntil(
      flushPendingSubmissions(env as unknown as Record<string, unknown>)
        .then((result) => {
          if (result.processed > 0) {
            console.log("Flushed pending form submissions:", result);
          }
        })
        .catch((error) => {
          console.error("Failed to flush pending form submissions:", error);
        }),
    );
  },
} satisfies ExportedHandler<CloudflareEnv>;
