// Custom Cloudflare Worker entry point.
//
// It re-uses the fetch handler generated by OpenNext and adds a scheduled
// handler that retries delivery of any form submissions whose notification
// email has not yet succeeded. This is what makes form delivery zero-loss:
// submissions are always stored in D1, and this cron keeps retrying the email
// until it goes through.
//
// Public GET responses are served from the Cache API when possible so visitors
// do not pay for a full Next.js render on every request (that path is what
// produced intermittent Error 1102). OpenNext is loaded only on a cache miss.

import { withPublicResponseCache } from "./lib/worker-public-cache";

type OpenNextWorker = {
  fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Response | Promise<Response>;
};

/** Keep local `wrangler dev` on http://localhost. */
function isLocalHostname(hostname: string): boolean {
  return (
    hostname === "localhost" ||
    hostname === "127.0.0.1" ||
    hostname === "[::1]" ||
    hostname.endsWith(".localhost")
  );
}

/**
 * Apex HTTP currently returns 200 (Always Use HTTPS is not on at the edge).
 * Google then lists those URLs as "Alternate page with proper canonical tag".
 * 308 to HTTPS so there is one indexable origin.
 */
function redirectHttpToHttps(request: Request): Response | null {
  const url = new URL(request.url);
  if (url.protocol !== "http:") return null;
  if (isLocalHostname(url.hostname)) return null;

  url.protocol = "https:";
  return Response.redirect(url.toString(), 308);
}

async function handleWithNext(
  request: Request,
  env: CloudflareEnv,
  ctx: ExecutionContext,
): Promise<Response> {
  // `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
  // Dynamically imported so cache hits never evaluate Next.js or middleware.
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore generated at build time
  const { default: handler } = (await import("./.open-next/worker.js")) as {
    default: OpenNextWorker;
  };
  return handler.fetch(request, env, ctx);
}

export default {
  fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Response | Promise<Response> {
    const httpsRedirect = redirectHttpToHttps(request);
    if (httpsRedirect) return httpsRedirect;

    return withPublicResponseCache(request, ctx, () =>
      handleWithNext(request, env, ctx),
    );
  },

  async scheduled(
    _event: ScheduledController,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ) {
    const { flushPendingSubmissions } = await import("./lib/form-delivery");
    ctx.waitUntil(
      flushPendingSubmissions(env as unknown as Record<string, unknown>)
        .then((result) => {
          if (result.processed > 0) {
            console.log("Flushed pending form submissions:", result);
          }
        })
        .catch((error) => {
          console.error("Failed to flush pending form submissions:", error);
        }),
    );
  },
} satisfies ExportedHandler<CloudflareEnv>;
