import { defineField, defineType } from "sanity";

export const eventsPage = defineType({
  name: "eventsPage",
  title: "Events page",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
  ],
  fieldsets: [
    {
      name: "archive",
      title: "Past events page",
      options: { collapsible: true, collapsed: true },
    },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Small Label",
      type: "string",
      group: "content",
      initialValue: "Events",
    }),
    defineField({
      name: "heroTitle",
      title: "Page Title",
      type: "string",
      group: "content",
      initialValue: "Upcoming events",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroDescription",
      title: "Page Introduction",
      type: "text",
      rows: 3,
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "emptyTitle",
      title: "Empty State Title",
      type: "string",
      group: "content",
      description: "Shown when there are no upcoming events.",
    }),
    defineField({
      name: "emptyDescription",
      title: "Empty State Text",
      type: "text",
      rows: 3,
      group: "content",
    }),
    defineField({
      name: "contactHeading",
      title: "Contact Section Heading",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "contactDescription",
      title: "Contact Section Text",
      type: "text",
      rows: 3,
      group: "content",
    }),
    defineField({
      name: "archiveEyebrow",
      title: "Past Events — Small Label",
      type: "string",
      group: "content",
      fieldset: "archive",
      initialValue: "Archive",
    }),
    defineField({
      name: "archiveTitle",
      title: "Past Events — Title",
      type: "string",
      group: "content",
      fieldset: "archive",
      initialValue: "Past events",
    }),
    defineField({
      name: "archiveDescription",
      title: "Past Events — Introduction",
      type: "text",
      rows: 2,
      group: "content",
      fieldset: "archive",
      initialValue: "A record of gatherings and sessions that have taken place.",
    }),
    defineField({
      name: "archiveEmptyTitle",
      title: "Past Events — Empty Title",
      type: "string",
      group: "content",
      fieldset: "archive",
      initialValue: "No past events yet",
    }),
    defineField({
      name: "archiveEmptyDescription",
      title: "Past Events — Empty Text",
      type: "text",
      rows: 2,
      group: "content",
      fieldset: "archive",
      initialValue: "Once events have taken place, they will appear here.",
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Events page" }),
  },
});
