import { defineField, defineType } from "sanity";

export const registerPage = defineType({
  name: "registerPage",
  title: "Registration form",
  type: "document",
  groups: [
    { name: "health", title: "Health step", default: true },
    { name: "disclaimer", title: "Medical disclaimer" },
    { name: "agreement", title: "Agreement step" },
    { name: "guidelines", title: "Guidelines" },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Small Label",
      type: "string",
      group: "health",
      initialValue: "Registration",
    }),
    defineField({
      name: "heroTitle",
      title: "Page Title",
      type: "string",
      group: "health",
      description:
        "Used when no event name is in the link. If someone opens a registration link for a named event, the title shows the event name and dates on two lines.",
      initialValue: "Program registration",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroDescription",
      title: "Page Introduction",
      type: "text",
      rows: 3,
      group: "health",
      initialValue:
        "Please complete the form below. Your information is confidential and is used only to prepare for your participation.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "healthIntro",
      title: "Health Step Introduction",
      type: "array",
      group: "health",
      of: [{ type: "text", rows: 3 }],
      description: "Paragraphs shown at the top of the health step.",
    }),
    defineField({
      name: "healthConditions",
      title: "Health Conditions",
      type: "array",
      group: "health",
      of: [{ type: "string" }],
      description:
        "The checkbox options for health conditions. “Other” and “NOT APPLICABLE” are always added automatically.",
    }),
    defineField({
      name: "healthDetailsLabel",
      title: "Health Details Question",
      type: "text",
      rows: 3,
      group: "health",
    }),
    defineField({
      name: "majorSurgeryQuestion",
      title: "Major Surgery Question",
      type: "string",
      group: "health",
    }),
    defineField({
      name: "majorSurgeryHint",
      title: "Major Surgery Hint",
      type: "text",
      rows: 3,
      group: "health",
    }),
    defineField({
      name: "pregnancyLabel",
      title: "Pregnancy Question",
      type: "string",
      group: "health",
    }),
    defineField({
      name: "disclaimerTitle",
      title: "Disclaimer Title",
      type: "string",
      group: "disclaimer",
      description: "Title of the disclaimer pop-up.",
    }),
    defineField({
      name: "disclaimerDocument",
      title: "Disclaimer Document",
      type: "array",
      group: "disclaimer",
      of: [{ type: "disclaimerSection" }],
      description: "The full disclaimer shown in the pop-up.",
    }),
    defineField({
      name: "disclaimerBullets",
      title: "Confirmation Bullets",
      type: "array",
      group: "disclaimer",
      of: [{ type: "text", rows: 2 }],
      description: "Shown under “By registering for the program, I confirm that:”.",
    }),
    defineField({
      name: "disclaimerConsentLabel",
      title: "Consent Checkbox Label",
      type: "text",
      rows: 2,
      group: "disclaimer",
    }),
    defineField({
      name: "refundPolicyBullets",
      title: "Refund Policy Bullets",
      type: "array",
      group: "agreement",
      of: [{ type: "text", rows: 2 }],
    }),
    defineField({
      name: "refundPolicyConsentLabel",
      title: "Refund Policy Consent Label",
      type: "string",
      group: "agreement",
    }),
    defineField({
      name: "agreementTitle",
      title: "Participant Agreement Title",
      type: "string",
      group: "agreement",
    }),
    defineField({
      name: "agreementBullets",
      title: "Participant Agreement Bullets",
      type: "array",
      group: "agreement",
      of: [{ type: "text", rows: 2 }],
    }),
    defineField({
      name: "agreementConsentLabel",
      title: "Agreement Consent Label",
      type: "string",
      group: "agreement",
    }),
    defineField({
      name: "beforeSessionBlocks",
      title: "“Before the Start of the Session” Blocks",
      type: "array",
      group: "guidelines",
      of: [{ type: "guidelineBlock" }],
      description: "The summary blocks shown on the final step of the form.",
    }),
    defineField({
      name: "guidelinesTitle",
      title: "Full Guidelines Title",
      type: "string",
      group: "guidelines",
      description: "Title of the full guidelines pop-up and PDF.",
    }),
    defineField({
      name: "guidelinesDocument",
      title: "Full Guidelines Document",
      type: "array",
      group: "guidelines",
      of: [{ type: "guidelineSection" }],
      description:
        "The full guidelines shown in the pop-up and used to generate the downloadable PDF.",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Registration form" }),
  },
});
