import { defineField, defineType } from "sanity";

export const retreatsPage = defineType({
  name: "retreatsPage",
  title: "Retreats page",
  type: "document",
  description:
    "Intro copy for /retreats (hero, Coming Soon, partner programs). Add actual retreats under Retreats, not here.",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
  ],
  fieldsets: [
    {
      name: "archive",
      title: "Past retreats page",
      options: { collapsible: true, collapsed: true },
    },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Small Label",
      type: "string",
      group: "content",
      initialValue: "Retreats & Partner Programs",
    }),
    defineField({
      name: "heroTitle",
      title: "Page Title",
      type: "string",
      group: "content",
      initialValue: "Classical Hatha Yoga retreats",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroDescription",
      title: "Page Introduction",
      type: "text",
      rows: 3,
      group: "content",
      description: "Short text shown below the page title.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "comingSoonEyebrow",
      title: "Coming Soon — Small Label",
      type: "string",
      group: "content",
      description: "Shown above the coming-soon heading when there are no upcoming retreats.",
      initialValue: "Coming Soon",
    }),
    defineField({
      name: "comingSoonHeading",
      title: "Coming Soon — Heading",
      type: "string",
      group: "content",
      description: "Shown when there are no upcoming retreats.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "comingSoonBody",
      title: "Coming Soon — Text",
      type: "text",
      rows: 4,
      group: "content",
      description: "Shown when there are no upcoming retreats.",
    }),
    defineField({
      name: "expectationsEyebrow",
      title: "What to Expect — Small Label",
      type: "string",
      group: "content",
      initialValue: "What to expect",
    }),
    defineField({
      name: "expectationsHeading",
      title: "What to Expect — Heading",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "expectations",
      title: "What to Expect — Cards",
      type: "array",
      group: "content",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "title", title: "Title", type: "string" }),
            defineField({ name: "body", title: "Text", type: "text", rows: 3 }),
          ],
          preview: { select: { title: "title", subtitle: "body" } },
        },
      ],
    }),
    defineField({
      name: "listingCta",
      title: "Retreats List — Call to Action",
      type: "object",
      group: "content",
      description: "Shown below the retreat cards when upcoming retreats are listed.",
      fields: [
        { name: "heading", title: "Heading", type: "string" },
        { name: "body", title: "Body", type: "text", rows: 2 },
        { name: "cta", title: "Button", type: "ctaLink" },
      ],
    }),
    defineField({
      name: "partnerPrograms",
      title: "Partner Programs",
      type: "object",
      group: "content",
      fields: [
        { name: "heading", title: "Heading", type: "string", validation: (rule) => rule.required() },
        {
          name: "intro",
          title: "Introduction Paragraphs",
          type: "array",
          of: [{ type: "text", rows: 3 }],
        },
        { name: "collaborateHeading", title: "Collaborate Heading", type: "string" },
        {
          name: "collaborateItems",
          title: "Collaborate List",
          type: "array",
          of: [{ type: "string" }],
        },
        {
          name: "closing",
          title: "Closing Paragraphs",
          type: "array",
          of: [{ type: "text", rows: 2 }],
        },
        {
          name: "whatsappPrefill",
          title: "WhatsApp Pre-filled Message",
          type: "string",
        },
      ],
    }),
    defineField({
      name: "archiveEyebrow",
      title: "Past Retreats — Small Label",
      type: "string",
      group: "content",
      fieldset: "archive",
      initialValue: "Archive",
    }),
    defineField({
      name: "archiveTitle",
      title: "Past Retreats — Title",
      type: "string",
      group: "content",
      fieldset: "archive",
      initialValue: "Past retreats",
    }),
    defineField({
      name: "archiveDescription",
      title: "Past Retreats — Introduction",
      type: "text",
      rows: 2,
      group: "content",
      fieldset: "archive",
      initialValue: "A record of immersive retreats that have taken place.",
    }),
    defineField({
      name: "archiveEmptyTitle",
      title: "Past Retreats — Empty Title",
      type: "string",
      group: "content",
      fieldset: "archive",
      initialValue: "No past retreats yet",
    }),
    defineField({
      name: "archiveEmptyDescription",
      title: "Past Retreats — Empty Text",
      type: "text",
      rows: 2,
      group: "content",
      fieldset: "archive",
      initialValue: "Once retreats have taken place, they will appear here.",
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Retreats page" }),
  },
});
