import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "seo", title: "SEO" },
  ],
  fieldsets: [
    { name: "brand", title: "Brand", options: { collapsible: false } },
    { name: "contact", title: "Contact", options: { collapsible: true, collapsed: false } },
    {
      name: "programs",
      title: "Program-wide Content",
      options: { collapsible: true, collapsed: false },
    },
  ],
  fields: [
    defineField({
      name: "brandName",
      title: "Business Name",
      type: "string",
      group: "content",
      fieldset: "brand",
      validation: (rule) => rule.required(),
      initialValue: "Nava Hatha Yoga",
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "content",
      fieldset: "brand",
      description: "A short line shown alongside the brand name in the footer.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "description",
      title: "Short Description",
      type: "text",
      rows: 3,
      group: "content",
      fieldset: "brand",
      description: "Used as a default description across the site and for SEO when a page has none.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "email",
      title: "Email",
      type: "string",
      group: "content",
      fieldset: "contact",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "phone",
      title: "Phone Number",
      type: "string",
      group: "content",
      fieldset: "contact",
    }),
    defineField({
      name: "whatsapp",
      title: "WhatsApp Number",
      type: "string",
      group: "content",
      fieldset: "contact",
      description:
        "Digits only, in international format without +, spaces, or symbols (for example 355690000000).",
    }),
    defineField({
      name: "location",
      title: "Location",
      type: "string",
      group: "content",
      fieldset: "contact",
      description: "General teaching location shown in search data (for example Saranda & Tirana, Albania).",
      initialValue: "Saranda & Tirana, Albania",
    }),
    defineField({
      name: "social",
      title: "Social Links",
      type: "array",
      group: "content",
      fieldset: "contact",
      of: [
        {
          type: "object",
          fields: [
            { name: "label", title: "Label", type: "string" },
            { name: "url", title: "URL", type: "url" },
          ],
          preview: {
            select: { title: "label", subtitle: "url" },
          },
        },
      ],
    }),
    defineField({
      name: "beforeProgramNotes",
      title: "Default Before-Program Notes",
      type: "array",
      group: "content",
      fieldset: "programs",
      of: [{ type: "string" }],
      description:
        "Used across multiple program pages. Shown in the “Before the Program” section unless that program has its own notes.",
    }),
    defineField({
      name: "bonusTitle",
      title: "Shared Bonus Title",
      type: "string",
      group: "content",
      fieldset: "programs",
      initialValue: "Bonus",
      description: "Used across multiple program pages. Heading of the Bonus box.",
    }),
    defineField({
      name: "bonusItems",
      title: "Shared Bonus Information",
      type: "array",
      group: "content",
      fieldset: "programs",
      of: [{ type: "string" }],
      description: "Used across multiple program pages. Shown in the Bonus box on every program page.",
    }),
    defineField({
      name: "discountNote",
      title: "Shared Discount Note",
      type: "string",
      group: "content",
      fieldset: "programs",
      description: "Used across multiple program pages. Shown under the Bonus box.",
    }),
    defineField({
      name: "medicalNoticeTitle",
      title: "Medical Notice Title",
      type: "string",
      group: "content",
      fieldset: "programs",
      initialValue: "Medical Notice!",
      description: "Used across multiple program pages.",
    }),
    defineField({
      name: "medicalNotice",
      title: "Medical Notice",
      type: "text",
      rows: 3,
      group: "content",
      fieldset: "programs",
      description:
        "Used across multiple program pages. Shown in the medical notice box on every program page.",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "eventExperienceNote",
      title: "Event Experience Note",
      type: "string",
      group: "content",
      fieldset: "programs",
      description:
        "Used across event cards when a related program has intensity set (for example “No prior yoga experience required!”).",
      initialValue: "No prior yoga experience required!",
    }),
    defineField({
      name: "seo",
      title: "Default SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    prepare: () => ({ title: "Site Settings" }),
  },
});
